### PR TITLE
Resolve #237 and #238

### LINKED ISSUE #237: [C2DMessageMonitor]the status is null after send C2D message to Device
repro on toolkit 2.1.0-rc

[C2DMessageMonitor] Start monitoring C2D message for [iotdevice]...
[C2DMessage] Sending message to [iotdevice] ...
[C2DMessage] [Success] Message sent to [iotdevice]
[C2DMessageMonitor] Message Received: send c2d message
[C2DMessageMonitor] Status: 

the status is null,  but expect is MessageCompleted.

### LINKED ISSUE #238: it will take about 5 second to response the stop action after click "Stop Monitoring D2C Message" in status bar
repro on : 2.1.0-rc

Right-click the title of tree explorer 
Click ‘Start monitoring D2C message’ 
Verify ‘Start monitoring’ message is shown in Output Channel 
Verify the is ‘Stop monitoring D2C message’ shown in Status Bar
Click ‘Stop monitoring D2C message’ in Status Bar

it will take about 5 second to response the stop action 
At first, I saw no response, and clicked the second time. then I see the stop result
image

### PR DESCRIPTION
**Pull request by formulahendry**
* Resolve #237: Disable webpack minimize to make 'constructor.name' work
* Resolve #238: Add hint when stopping monitoring D2C message

### CODE REVIEW

**Comment by adashen** [comment]
Do we really need res.constructor.name to get the the constructor name for status? From api document. The signature is [function complete(message: Message, done: (err?: Error, result?: MessageCompleted) => void)](https://docs.microsoft.com/en-us/javascript/api/azure-iot-device/DeviceTransport?view=azure-node-latest#complete-message---err---error--result---messagecompleted-----void-)

**Comment by formulahendry** [comment]
@adashen The `MessageCompleted` in `result?: MessageCompleted` is just type annotation in TypeScript world for static analysis. In runtime, the info is not carried, res.constructor.name is the only way. Docs also use the method: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-c2d#send-a-cloud-to-device-message

**Comment by adashen** [comment]
@formulahendry. I know it is static annotation, but if the name is already fixed to "MessageCompleted", there is no need to get from constructor. I saw the example, the code getting name from constructor, because the print method is shared between different events (complete, send...)

**Comment by formulahendry** [comment]
@adashen Got your point. I think we'd better still use the `res.constructor.name` in case the parameter would change to something like `result?: MessageCompleted | MessageFailed`, we do not need update the code. It is more scalable. I don't want to just workaround for webpack minimization to change this kind of code, as long-term we still may use `res.constructor.name` or other similar method.  We want to leverage https://github.com/terser-js/terser#minify-options to keep minimization and avoid missing  `res.constructor.name`. There is a task to track this: https://github.com/Microsoft/vscode-azure-iot-toolkit/issues/240

**Pull request merged**
